import { Navbar } from '@/components/navbar';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const items = [
  { title: 'Our Story', href: '/our-story' },
  // { title: 'Photos', href: '/photos' },
  // { title: 'Q & A', href: '/q-and-a' },
  // { title: 'Travel', href: '/travel' },
  // { title: 'Registry', href: '/registry' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="z-10">
          <Navbar items={items} />
        </header>
        {children}
      </body>
    </html>
  );
}
