/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-vercel-postgres';
import { relations } from '@payloadcms/db-vercel-postgres/drizzle';
import {
  boolean,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
  varchar,
  type AnyPgColumn,
} from '@payloadcms/db-vercel-postgres/drizzle/pg-core';
export const enum_honeymoon_contributions_status = pgEnum(
  'enum_honeymoon_contributions_status',
  ['pending', 'completed', 'failed'],
);
export const enum_pages_blocks_content_columns_size = pgEnum(
  'enum_pages_blocks_content_columns_size',
  ['oneThird', 'half', 'twoThirds', 'full'],
);
export const enum_pages_blocks_photo_gallery_folder = pgEnum(
  'enum_pages_blocks_photo_gallery_folder',
  ['Barn'],
);
export const enum_pages_blocks_stack_direction = pgEnum(
  'enum_pages_blocks_stack_direction',
  ['vertical', 'horizontal'],
);
export const enum_pages_status = pgEnum('enum_pages_status', [
  'draft',
  'published',
]);
export const enum__pages_v_blocks_content_columns_size = pgEnum(
  'enum__pages_v_blocks_content_columns_size',
  ['oneThird', 'half', 'twoThirds', 'full'],
);
export const enum__pages_v_blocks_photo_gallery_folder = pgEnum(
  'enum__pages_v_blocks_photo_gallery_folder',
  ['Barn'],
);
export const enum__pages_v_blocks_stack_direction = pgEnum(
  'enum__pages_v_blocks_stack_direction',
  ['vertical', 'horizontal'],
);
export const enum__pages_v_version_status = pgEnum(
  'enum__pages_v_version_status',
  ['draft', 'published'],
);
export const enum_registry_purchase_purchased_at = pgEnum(
  'enum_registry_purchase_purchased_at',
  ['online', 'in-store'],
);
export const enum_payload_folders_folder_type = pgEnum(
  'enum_payload_folders_folder_type',
  ['photo'],
);

export const honeymoon_contributions = pgTable(
  'honeymoon_contributions',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    email: varchar('email'),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    message: varchar('message'),
    stripePaymentIntentId: varchar('stripe_payment_intent_id').notNull(),
    status: enum_honeymoon_contributions_status('status').default('pending'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('honeymoon_contributions_stripe_payment_intent_id_idx').on(
      columns.stripePaymentIntentId,
    ),
    index('honeymoon_contributions_updated_at_idx').on(columns.updatedAt),
    index('honeymoon_contributions_created_at_idx').on(columns.createdAt),
  ],
);

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
);

export const pages_blocks_accordion_items = pgTable(
  'pages_blocks_accordion_items',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    content: jsonb('content'),
  },
  (columns) => [
    index('pages_blocks_accordion_items_order_idx').on(columns._order),
    index('pages_blocks_accordion_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_accordion.id],
      name: 'pages_blocks_accordion_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const pages_blocks_accordion = pgTable(
  'pages_blocks_accordion',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_accordion_order_idx').on(columns._order),
    index('pages_blocks_accordion_parent_id_idx').on(columns._parentID),
    index('pages_blocks_accordion_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_accordion_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const pages_blocks_card = pgTable(
  'pages_blocks_card',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_card_order_idx').on(columns._order),
    index('pages_blocks_card_parent_id_idx').on(columns._parentID),
    index('pages_blocks_card_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_card_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const pages_blocks_content_columns = pgTable(
  'pages_blocks_content_columns',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    size: enum_pages_blocks_content_columns_size('size').default('full'),
    richText: jsonb('rich_text'),
  },
  (columns) => [
    index('pages_blocks_content_columns_order_idx').on(columns._order),
    index('pages_blocks_content_columns_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_content.id],
      name: 'pages_blocks_content_columns_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const pages_blocks_content = pgTable(
  'pages_blocks_content',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    separator: boolean('separator').default(false),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_content_order_idx').on(columns._order),
    index('pages_blocks_content_parent_id_idx').on(columns._parentID),
    index('pages_blocks_content_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_content_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const pages_blocks_photo_gallery = pgTable(
  'pages_blocks_photo_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    folder: enum_pages_blocks_photo_gallery_folder('folder'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_photo_gallery_order_idx').on(columns._order),
    index('pages_blocks_photo_gallery_parent_id_idx').on(columns._parentID),
    index('pages_blocks_photo_gallery_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_photo_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const pages_blocks_place = pgTable(
  'pages_blocks_place',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    description: jsonb('description'),
    url: varchar('url'),
    location: varchar('location'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_place_order_idx').on(columns._order),
    index('pages_blocks_place_parent_id_idx').on(columns._parentID),
    index('pages_blocks_place_path_idx').on(columns._path),
    index('pages_blocks_place_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_place_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const pages_blocks_registry = pgTable(
  'pages_blocks_registry',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_registry_order_idx').on(columns._order),
    index('pages_blocks_registry_parent_id_idx').on(columns._parentID),
    index('pages_blocks_registry_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_registry_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const pages_blocks_schedule_events = pgTable(
  'pages_blocks_schedule_events',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    date: timestamp('date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).default('Sat Sep 06 2025 00:00:00 GMT-0400 (Eastern Daylight Time)'),
    time: varchar('time'),
    description: jsonb('description'),
    location: varchar('location'),
    attire: varchar('attire'),
    draft: boolean('draft').default(false),
  },
  (columns) => [
    index('pages_blocks_schedule_events_order_idx').on(columns._order),
    index('pages_blocks_schedule_events_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_schedule.id],
      name: 'pages_blocks_schedule_events_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const pages_blocks_schedule = pgTable(
  'pages_blocks_schedule',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_schedule_order_idx').on(columns._order),
    index('pages_blocks_schedule_parent_id_idx').on(columns._parentID),
    index('pages_blocks_schedule_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_schedule_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const pages_blocks_stack = pgTable(
  'pages_blocks_stack',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    direction:
      enum_pages_blocks_stack_direction('direction').default('vertical'),
    wrap: boolean('wrap').default(false),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_stack_order_idx').on(columns._order),
    index('pages_blocks_stack_parent_id_idx').on(columns._parentID),
    index('pages_blocks_stack_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_stack_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const pages_blocks_things_to_do = pgTable(
  'pages_blocks_things_to_do',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_things_to_do_order_idx').on(columns._order),
    index('pages_blocks_things_to_do_parent_id_idx').on(columns._parentID),
    index('pages_blocks_things_to_do_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_things_to_do_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status('_status').default('draft'),
  },
  (columns) => [
    index('pages_slug_idx').on(columns.slug),
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
    index('pages__status_idx').on(columns._status),
  ],
);

export const pages_rels = pgTable(
  'pages_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'place-tagID': integer('place_tag_id'),
    'registry-itemID': integer('registry_item_id'),
    'things-to-do-categoryID': integer('things_to_do_category_id'),
    'things-to-doID': integer('things_to_do_id'),
  },
  (columns) => [
    index('pages_rels_order_idx').on(columns.order),
    index('pages_rels_parent_idx').on(columns.parent),
    index('pages_rels_path_idx').on(columns.path),
    index('pages_rels_place_tag_id_idx').on(columns['place-tagID']),
    index('pages_rels_registry_item_id_idx').on(columns['registry-itemID']),
    index('pages_rels_things_to_do_category_id_idx').on(
      columns['things-to-do-categoryID'],
    ),
    index('pages_rels_things_to_do_id_idx').on(columns['things-to-doID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [pages.id],
      name: 'pages_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['place-tagID']],
      foreignColumns: [place_tag.id],
      name: 'pages_rels_place_tag_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['registry-itemID']],
      foreignColumns: [registry_item.id],
      name: 'pages_rels_registry_item_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['things-to-do-categoryID']],
      foreignColumns: [things_to_do_category.id],
      name: 'pages_rels_things_to_do_category_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['things-to-doID']],
      foreignColumns: [things_to_do.id],
      name: 'pages_rels_things_to_do_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v_blocks_accordion_items = pgTable(
  '_pages_v_blocks_accordion_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    title: varchar('title'),
    content: jsonb('content'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_pages_v_blocks_accordion_items_order_idx').on(columns._order),
    index('_pages_v_blocks_accordion_items_parent_id_idx').on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v_blocks_accordion.id],
      name: '_pages_v_blocks_accordion_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v_blocks_accordion = pgTable(
  '_pages_v_blocks_accordion',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_accordion_order_idx').on(columns._order),
    index('_pages_v_blocks_accordion_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_accordion_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_accordion_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v_blocks_card = pgTable(
  '_pages_v_blocks_card',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    title: varchar('title'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_card_order_idx').on(columns._order),
    index('_pages_v_blocks_card_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_card_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_card_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v_blocks_content_columns = pgTable(
  '_pages_v_blocks_content_columns',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    size: enum__pages_v_blocks_content_columns_size('size').default('full'),
    richText: jsonb('rich_text'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_pages_v_blocks_content_columns_order_idx').on(columns._order),
    index('_pages_v_blocks_content_columns_parent_id_idx').on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v_blocks_content.id],
      name: '_pages_v_blocks_content_columns_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v_blocks_content = pgTable(
  '_pages_v_blocks_content',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    separator: boolean('separator').default(false),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_content_order_idx').on(columns._order),
    index('_pages_v_blocks_content_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_content_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_content_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v_blocks_photo_gallery = pgTable(
  '_pages_v_blocks_photo_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    folder: enum__pages_v_blocks_photo_gallery_folder('folder'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_photo_gallery_order_idx').on(columns._order),
    index('_pages_v_blocks_photo_gallery_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_photo_gallery_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_photo_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v_blocks_place = pgTable(
  '_pages_v_blocks_place',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    title: varchar('title'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    description: jsonb('description'),
    url: varchar('url'),
    location: varchar('location'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_place_order_idx').on(columns._order),
    index('_pages_v_blocks_place_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_place_path_idx').on(columns._path),
    index('_pages_v_blocks_place_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_place_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v_blocks_registry = pgTable(
  '_pages_v_blocks_registry',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_registry_order_idx').on(columns._order),
    index('_pages_v_blocks_registry_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_registry_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_registry_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v_blocks_schedule_events = pgTable(
  '_pages_v_blocks_schedule_events',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    title: varchar('title'),
    date: timestamp('date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).default('Sat Sep 06 2025 00:00:00 GMT-0400 (Eastern Daylight Time)'),
    time: varchar('time'),
    description: jsonb('description'),
    location: varchar('location'),
    attire: varchar('attire'),
    draft: boolean('draft').default(false),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_pages_v_blocks_schedule_events_order_idx').on(columns._order),
    index('_pages_v_blocks_schedule_events_parent_id_idx').on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v_blocks_schedule.id],
      name: '_pages_v_blocks_schedule_events_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v_blocks_schedule = pgTable(
  '_pages_v_blocks_schedule',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_schedule_order_idx').on(columns._order),
    index('_pages_v_blocks_schedule_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_schedule_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_schedule_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v_blocks_stack = pgTable(
  '_pages_v_blocks_stack',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    direction:
      enum__pages_v_blocks_stack_direction('direction').default('vertical'),
    wrap: boolean('wrap').default(false),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_stack_order_idx').on(columns._order),
    index('_pages_v_blocks_stack_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_stack_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_stack_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v_blocks_things_to_do = pgTable(
  '_pages_v_blocks_things_to_do',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_things_to_do_order_idx').on(columns._order),
    index('_pages_v_blocks_things_to_do_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_things_to_do_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_things_to_do_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const _pages_v = pgTable(
  '_pages_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => pages.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__pages_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => [
    index('_pages_v_parent_idx').on(columns.parent),
    index('_pages_v_version_version_slug_idx').on(columns.version_slug),
    index('_pages_v_version_version_updated_at_idx').on(
      columns.version_updatedAt,
    ),
    index('_pages_v_version_version_created_at_idx').on(
      columns.version_createdAt,
    ),
    index('_pages_v_version_version__status_idx').on(columns.version__status),
    index('_pages_v_created_at_idx').on(columns.createdAt),
    index('_pages_v_updated_at_idx').on(columns.updatedAt),
    index('_pages_v_latest_idx').on(columns.latest),
    index('_pages_v_autosave_idx').on(columns.autosave),
  ],
);

export const _pages_v_rels = pgTable(
  '_pages_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'place-tagID': integer('place_tag_id'),
    'registry-itemID': integer('registry_item_id'),
    'things-to-do-categoryID': integer('things_to_do_category_id'),
    'things-to-doID': integer('things_to_do_id'),
  },
  (columns) => [
    index('_pages_v_rels_order_idx').on(columns.order),
    index('_pages_v_rels_parent_idx').on(columns.parent),
    index('_pages_v_rels_path_idx').on(columns.path),
    index('_pages_v_rels_place_tag_id_idx').on(columns['place-tagID']),
    index('_pages_v_rels_registry_item_id_idx').on(columns['registry-itemID']),
    index('_pages_v_rels_things_to_do_category_id_idx').on(
      columns['things-to-do-categoryID'],
    ),
    index('_pages_v_rels_things_to_do_id_idx').on(columns['things-to-doID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['place-tagID']],
      foreignColumns: [place_tag.id],
      name: '_pages_v_rels_place_tag_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['registry-itemID']],
      foreignColumns: [registry_item.id],
      name: '_pages_v_rels_registry_item_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['things-to-do-categoryID']],
      foreignColumns: [things_to_do_category.id],
      name: '_pages_v_rels_things_to_do_category_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['things-to-doID']],
      foreignColumns: [things_to_do.id],
      name: '_pages_v_rels_things_to_do_fk',
    }).onDelete('cascade'),
  ],
);

export const photo = pgTable(
  'photo',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    folder: integer('folder_id').references(() => payload_folders.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('photo_folder_idx').on(columns.folder),
    index('photo_updated_at_idx').on(columns.updatedAt),
    index('photo_created_at_idx').on(columns.createdAt),
    uniqueIndex('photo_filename_idx').on(columns.filename),
  ],
);

export const place_tag = pgTable(
  'place_tag',
  {
    id: serial('id').primaryKey(),
    label: varchar('label').notNull(),
    slug: varchar('slug').notNull(),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('place_tag_slug_idx').on(columns.slug),
    index('place_tag_updated_at_idx').on(columns.updatedAt),
    index('place_tag_created_at_idx').on(columns.createdAt),
  ],
);

export const registry_category = pgTable(
  'registry_category',
  {
    id: serial('id').primaryKey(),
    label: varchar('label').notNull(),
    slug: varchar('slug').notNull(),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('registry_category_slug_idx').on(columns.slug),
    index('registry_category_updated_at_idx').on(columns.updatedAt),
    index('registry_category_created_at_idx').on(columns.createdAt),
  ],
);

export const registry_item = pgTable(
  'registry_item',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    description: jsonb('description'),
    store: integer('store_id').references(() => registry_store.id, {
      onDelete: 'set null',
    }),
    price: numeric('price', { mode: 'number' }).notNull(),
    url: varchar('url').notNull(),
    quantityRequested: numeric('quantity_requested', { mode: 'number' }),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('registry_item_store_idx').on(columns.store),
    index('registry_item_image_idx').on(columns.image),
    index('registry_item_updated_at_idx').on(columns.updatedAt),
    index('registry_item_created_at_idx').on(columns.createdAt),
  ],
);

export const registry_item_rels = pgTable(
  'registry_item_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'registry-categoryID': integer('registry_category_id'),
  },
  (columns) => [
    index('registry_item_rels_order_idx').on(columns.order),
    index('registry_item_rels_parent_idx').on(columns.parent),
    index('registry_item_rels_path_idx').on(columns.path),
    index('registry_item_rels_registry_category_id_idx').on(
      columns['registry-categoryID'],
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [registry_item.id],
      name: 'registry_item_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['registry-categoryID']],
      foreignColumns: [registry_category.id],
      name: 'registry_item_rels_registry_category_fk',
    }).onDelete('cascade'),
  ],
);

export const registry_purchase = pgTable(
  'registry_purchase',
  {
    id: serial('id').primaryKey(),
    registryItem: integer('registry_item_id')
      .notNull()
      .references(() => registry_item.id, {
        onDelete: 'set null',
      }),
    quantity: numeric('quantity', { mode: 'number' }).notNull(),
    purchasedAt: enum_registry_purchase_purchased_at('purchased_at').notNull(),
    orderNumber: varchar('order_number'),
    purchaserName: varchar('purchaser_name').notNull(),
    purchaserEmail: varchar('purchaser_email'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('registry_purchase_registry_item_idx').on(columns.registryItem),
    index('registry_purchase_updated_at_idx').on(columns.updatedAt),
    index('registry_purchase_created_at_idx').on(columns.createdAt),
  ],
);

export const registry_store = pgTable(
  'registry_store',
  {
    id: serial('id').primaryKey(),
    label: varchar('label').notNull(),
    slug: varchar('slug').notNull(),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('registry_store_slug_idx').on(columns.slug),
    index('registry_store_updated_at_idx').on(columns.updatedAt),
    index('registry_store_created_at_idx').on(columns.createdAt),
  ],
);

export const things_to_do = pgTable(
  'things_to_do',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    description: varchar('description').notNull(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('things_to_do_image_idx').on(columns.image),
    index('things_to_do_updated_at_idx').on(columns.updatedAt),
    index('things_to_do_created_at_idx').on(columns.createdAt),
  ],
);

export const things_to_do_rels = pgTable(
  'things_to_do_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'things-to-do-categoryID': integer('things_to_do_category_id'),
  },
  (columns) => [
    index('things_to_do_rels_order_idx').on(columns.order),
    index('things_to_do_rels_parent_idx').on(columns.parent),
    index('things_to_do_rels_path_idx').on(columns.path),
    index('things_to_do_rels_things_to_do_category_id_idx').on(
      columns['things-to-do-categoryID'],
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [things_to_do.id],
      name: 'things_to_do_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['things-to-do-categoryID']],
      foreignColumns: [things_to_do_category.id],
      name: 'things_to_do_rels_things_to_do_category_fk',
    }).onDelete('cascade'),
  ],
);

export const things_to_do_category = pgTable(
  'things_to_do_category',
  {
    id: serial('id').primaryKey(),
    label: varchar('label').notNull(),
    slug: varchar('slug').notNull(),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('things_to_do_category_slug_idx').on(columns.slug),
    index('things_to_do_category_updated_at_idx').on(columns.updatedAt),
    index('things_to_do_category_created_at_idx').on(columns.createdAt),
  ],
);

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
);

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
);

export const payload_folders_folder_type = pgTable(
  'payload_folders_folder_type',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_payload_folders_folder_type('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('payload_folders_folder_type_order_idx').on(columns.order),
    index('payload_folders_folder_type_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_folders.id],
      name: 'payload_folders_folder_type_parent_fk',
    }).onDelete('cascade'),
  ],
);

export const payload_folders = pgTable(
  'payload_folders',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    folder: integer('folder_id').references(
      (): AnyPgColumn => payload_folders.id,
      {
        onDelete: 'set null',
      },
    ),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_folders_name_idx').on(columns.name),
    index('payload_folders_folder_idx').on(columns.folder),
    index('payload_folders_updated_at_idx').on(columns.updatedAt),
    index('payload_folders_created_at_idx').on(columns.createdAt),
  ],
);

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'honeymoon-contributionsID': integer('honeymoon_contributions_id'),
    mediaID: integer('media_id'),
    pagesID: integer('pages_id'),
    photoID: integer('photo_id'),
    'place-tagID': integer('place_tag_id'),
    'registry-categoryID': integer('registry_category_id'),
    'registry-itemID': integer('registry_item_id'),
    'registry-purchaseID': integer('registry_purchase_id'),
    'registry-storeID': integer('registry_store_id'),
    'things-to-doID': integer('things_to_do_id'),
    'things-to-do-categoryID': integer('things_to_do_category_id'),
    usersID: integer('users_id'),
    'payload-foldersID': integer('payload_folders_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_honeymoon_contributions_id_idx').on(
      columns['honeymoon-contributionsID'],
    ),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_photo_id_idx').on(columns.photoID),
    index('payload_locked_documents_rels_place_tag_id_idx').on(
      columns['place-tagID'],
    ),
    index('payload_locked_documents_rels_registry_category_id_idx').on(
      columns['registry-categoryID'],
    ),
    index('payload_locked_documents_rels_registry_item_id_idx').on(
      columns['registry-itemID'],
    ),
    index('payload_locked_documents_rels_registry_purchase_id_idx').on(
      columns['registry-purchaseID'],
    ),
    index('payload_locked_documents_rels_registry_store_id_idx').on(
      columns['registry-storeID'],
    ),
    index('payload_locked_documents_rels_things_to_do_id_idx').on(
      columns['things-to-doID'],
    ),
    index('payload_locked_documents_rels_things_to_do_category_id_idx').on(
      columns['things-to-do-categoryID'],
    ),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_payload_folders_id_idx').on(
      columns['payload-foldersID'],
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['honeymoon-contributionsID']],
      foreignColumns: [honeymoon_contributions.id],
      name: 'payload_locked_documents_rels_honeymoon_contributions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['photoID']],
      foreignColumns: [photo.id],
      name: 'payload_locked_documents_rels_photo_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['place-tagID']],
      foreignColumns: [place_tag.id],
      name: 'payload_locked_documents_rels_place_tag_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['registry-categoryID']],
      foreignColumns: [registry_category.id],
      name: 'payload_locked_documents_rels_registry_category_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['registry-itemID']],
      foreignColumns: [registry_item.id],
      name: 'payload_locked_documents_rels_registry_item_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['registry-purchaseID']],
      foreignColumns: [registry_purchase.id],
      name: 'payload_locked_documents_rels_registry_purchase_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['registry-storeID']],
      foreignColumns: [registry_store.id],
      name: 'payload_locked_documents_rels_registry_store_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['things-to-doID']],
      foreignColumns: [things_to_do.id],
      name: 'payload_locked_documents_rels_things_to_do_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['things-to-do-categoryID']],
      foreignColumns: [things_to_do_category.id],
      name: 'payload_locked_documents_rels_things_to_do_category_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['payload-foldersID']],
      foreignColumns: [payload_folders.id],
      name: 'payload_locked_documents_rels_payload_folders_fk',
    }).onDelete('cascade'),
  ],
);

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
);

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
);

export const relations_honeymoon_contributions = relations(
  honeymoon_contributions,
  () => ({}),
);
export const relations_media = relations(media, () => ({}));
export const relations_pages_blocks_accordion_items = relations(
  pages_blocks_accordion_items,
  ({ one }) => ({
    _parentID: one(pages_blocks_accordion, {
      fields: [pages_blocks_accordion_items._parentID],
      references: [pages_blocks_accordion.id],
      relationName: 'items',
    }),
  }),
);
export const relations_pages_blocks_accordion = relations(
  pages_blocks_accordion,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_accordion._parentID],
      references: [pages.id],
      relationName: '_blocks_accordion',
    }),
    items: many(pages_blocks_accordion_items, {
      relationName: 'items',
    }),
  }),
);
export const relations_pages_blocks_card = relations(
  pages_blocks_card,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_card._parentID],
      references: [pages.id],
      relationName: '_blocks_card',
    }),
  }),
);
export const relations_pages_blocks_content_columns = relations(
  pages_blocks_content_columns,
  ({ one }) => ({
    _parentID: one(pages_blocks_content, {
      fields: [pages_blocks_content_columns._parentID],
      references: [pages_blocks_content.id],
      relationName: 'columns',
    }),
  }),
);
export const relations_pages_blocks_content = relations(
  pages_blocks_content,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_content._parentID],
      references: [pages.id],
      relationName: '_blocks_content',
    }),
    columns: many(pages_blocks_content_columns, {
      relationName: 'columns',
    }),
  }),
);
export const relations_pages_blocks_photo_gallery = relations(
  pages_blocks_photo_gallery,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_photo_gallery._parentID],
      references: [pages.id],
      relationName: '_blocks_photo-gallery',
    }),
  }),
);
export const relations_pages_blocks_place = relations(
  pages_blocks_place,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_place._parentID],
      references: [pages.id],
      relationName: '_blocks_place',
    }),
    image: one(media, {
      fields: [pages_blocks_place.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
);
export const relations_pages_blocks_registry = relations(
  pages_blocks_registry,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_registry._parentID],
      references: [pages.id],
      relationName: '_blocks_registry',
    }),
  }),
);
export const relations_pages_blocks_schedule_events = relations(
  pages_blocks_schedule_events,
  ({ one }) => ({
    _parentID: one(pages_blocks_schedule, {
      fields: [pages_blocks_schedule_events._parentID],
      references: [pages_blocks_schedule.id],
      relationName: 'events',
    }),
  }),
);
export const relations_pages_blocks_schedule = relations(
  pages_blocks_schedule,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_schedule._parentID],
      references: [pages.id],
      relationName: '_blocks_schedule',
    }),
    events: many(pages_blocks_schedule_events, {
      relationName: 'events',
    }),
  }),
);
export const relations_pages_blocks_stack = relations(
  pages_blocks_stack,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_stack._parentID],
      references: [pages.id],
      relationName: '_blocks_stack',
    }),
  }),
);
export const relations_pages_blocks_things_to_do = relations(
  pages_blocks_things_to_do,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_things_to_do._parentID],
      references: [pages.id],
      relationName: '_blocks_things-to-do',
    }),
  }),
);
export const relations_pages_rels = relations(pages_rels, ({ one }) => ({
  parent: one(pages, {
    fields: [pages_rels.parent],
    references: [pages.id],
    relationName: '_rels',
  }),
  'place-tagID': one(place_tag, {
    fields: [pages_rels['place-tagID']],
    references: [place_tag.id],
    relationName: 'place-tag',
  }),
  'registry-itemID': one(registry_item, {
    fields: [pages_rels['registry-itemID']],
    references: [registry_item.id],
    relationName: 'registry-item',
  }),
  'things-to-do-categoryID': one(things_to_do_category, {
    fields: [pages_rels['things-to-do-categoryID']],
    references: [things_to_do_category.id],
    relationName: 'things-to-do-category',
  }),
  'things-to-doID': one(things_to_do, {
    fields: [pages_rels['things-to-doID']],
    references: [things_to_do.id],
    relationName: 'things-to-do',
  }),
}));
export const relations_pages = relations(pages, ({ many }) => ({
  _blocks_accordion: many(pages_blocks_accordion, {
    relationName: '_blocks_accordion',
  }),
  _blocks_card: many(pages_blocks_card, {
    relationName: '_blocks_card',
  }),
  _blocks_content: many(pages_blocks_content, {
    relationName: '_blocks_content',
  }),
  '_blocks_photo-gallery': many(pages_blocks_photo_gallery, {
    relationName: '_blocks_photo-gallery',
  }),
  _blocks_place: many(pages_blocks_place, {
    relationName: '_blocks_place',
  }),
  _blocks_registry: many(pages_blocks_registry, {
    relationName: '_blocks_registry',
  }),
  _blocks_schedule: many(pages_blocks_schedule, {
    relationName: '_blocks_schedule',
  }),
  _blocks_stack: many(pages_blocks_stack, {
    relationName: '_blocks_stack',
  }),
  '_blocks_things-to-do': many(pages_blocks_things_to_do, {
    relationName: '_blocks_things-to-do',
  }),
  _rels: many(pages_rels, {
    relationName: '_rels',
  }),
}));
export const relations__pages_v_blocks_accordion_items = relations(
  _pages_v_blocks_accordion_items,
  ({ one }) => ({
    _parentID: one(_pages_v_blocks_accordion, {
      fields: [_pages_v_blocks_accordion_items._parentID],
      references: [_pages_v_blocks_accordion.id],
      relationName: 'items',
    }),
  }),
);
export const relations__pages_v_blocks_accordion = relations(
  _pages_v_blocks_accordion,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_accordion._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_accordion',
    }),
    items: many(_pages_v_blocks_accordion_items, {
      relationName: 'items',
    }),
  }),
);
export const relations__pages_v_blocks_card = relations(
  _pages_v_blocks_card,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_card._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_card',
    }),
  }),
);
export const relations__pages_v_blocks_content_columns = relations(
  _pages_v_blocks_content_columns,
  ({ one }) => ({
    _parentID: one(_pages_v_blocks_content, {
      fields: [_pages_v_blocks_content_columns._parentID],
      references: [_pages_v_blocks_content.id],
      relationName: 'columns',
    }),
  }),
);
export const relations__pages_v_blocks_content = relations(
  _pages_v_blocks_content,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_content._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_content',
    }),
    columns: many(_pages_v_blocks_content_columns, {
      relationName: 'columns',
    }),
  }),
);
export const relations__pages_v_blocks_photo_gallery = relations(
  _pages_v_blocks_photo_gallery,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_photo_gallery._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_photo-gallery',
    }),
  }),
);
export const relations__pages_v_blocks_place = relations(
  _pages_v_blocks_place,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_place._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_place',
    }),
    image: one(media, {
      fields: [_pages_v_blocks_place.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
);
export const relations__pages_v_blocks_registry = relations(
  _pages_v_blocks_registry,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_registry._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_registry',
    }),
  }),
);
export const relations__pages_v_blocks_schedule_events = relations(
  _pages_v_blocks_schedule_events,
  ({ one }) => ({
    _parentID: one(_pages_v_blocks_schedule, {
      fields: [_pages_v_blocks_schedule_events._parentID],
      references: [_pages_v_blocks_schedule.id],
      relationName: 'events',
    }),
  }),
);
export const relations__pages_v_blocks_schedule = relations(
  _pages_v_blocks_schedule,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_schedule._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_schedule',
    }),
    events: many(_pages_v_blocks_schedule_events, {
      relationName: 'events',
    }),
  }),
);
export const relations__pages_v_blocks_stack = relations(
  _pages_v_blocks_stack,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_stack._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_stack',
    }),
  }),
);
export const relations__pages_v_blocks_things_to_do = relations(
  _pages_v_blocks_things_to_do,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_things_to_do._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_things-to-do',
    }),
  }),
);
export const relations__pages_v_rels = relations(_pages_v_rels, ({ one }) => ({
  parent: one(_pages_v, {
    fields: [_pages_v_rels.parent],
    references: [_pages_v.id],
    relationName: '_rels',
  }),
  'place-tagID': one(place_tag, {
    fields: [_pages_v_rels['place-tagID']],
    references: [place_tag.id],
    relationName: 'place-tag',
  }),
  'registry-itemID': one(registry_item, {
    fields: [_pages_v_rels['registry-itemID']],
    references: [registry_item.id],
    relationName: 'registry-item',
  }),
  'things-to-do-categoryID': one(things_to_do_category, {
    fields: [_pages_v_rels['things-to-do-categoryID']],
    references: [things_to_do_category.id],
    relationName: 'things-to-do-category',
  }),
  'things-to-doID': one(things_to_do, {
    fields: [_pages_v_rels['things-to-doID']],
    references: [things_to_do.id],
    relationName: 'things-to-do',
  }),
}));
export const relations__pages_v = relations(_pages_v, ({ one, many }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: 'parent',
  }),
  _blocks_accordion: many(_pages_v_blocks_accordion, {
    relationName: '_blocks_accordion',
  }),
  _blocks_card: many(_pages_v_blocks_card, {
    relationName: '_blocks_card',
  }),
  _blocks_content: many(_pages_v_blocks_content, {
    relationName: '_blocks_content',
  }),
  '_blocks_photo-gallery': many(_pages_v_blocks_photo_gallery, {
    relationName: '_blocks_photo-gallery',
  }),
  _blocks_place: many(_pages_v_blocks_place, {
    relationName: '_blocks_place',
  }),
  _blocks_registry: many(_pages_v_blocks_registry, {
    relationName: '_blocks_registry',
  }),
  _blocks_schedule: many(_pages_v_blocks_schedule, {
    relationName: '_blocks_schedule',
  }),
  _blocks_stack: many(_pages_v_blocks_stack, {
    relationName: '_blocks_stack',
  }),
  '_blocks_things-to-do': many(_pages_v_blocks_things_to_do, {
    relationName: '_blocks_things-to-do',
  }),
  _rels: many(_pages_v_rels, {
    relationName: '_rels',
  }),
}));
export const relations_photo = relations(photo, ({ one }) => ({
  folder: one(payload_folders, {
    fields: [photo.folder],
    references: [payload_folders.id],
    relationName: 'folder',
  }),
}));
export const relations_place_tag = relations(place_tag, () => ({}));
export const relations_registry_category = relations(
  registry_category,
  () => ({}),
);
export const relations_registry_item_rels = relations(
  registry_item_rels,
  ({ one }) => ({
    parent: one(registry_item, {
      fields: [registry_item_rels.parent],
      references: [registry_item.id],
      relationName: '_rels',
    }),
    'registry-categoryID': one(registry_category, {
      fields: [registry_item_rels['registry-categoryID']],
      references: [registry_category.id],
      relationName: 'registry-category',
    }),
  }),
);
export const relations_registry_item = relations(
  registry_item,
  ({ one, many }) => ({
    store: one(registry_store, {
      fields: [registry_item.store],
      references: [registry_store.id],
      relationName: 'store',
    }),
    image: one(media, {
      fields: [registry_item.image],
      references: [media.id],
      relationName: 'image',
    }),
    _rels: many(registry_item_rels, {
      relationName: '_rels',
    }),
  }),
);
export const relations_registry_purchase = relations(
  registry_purchase,
  ({ one }) => ({
    registryItem: one(registry_item, {
      fields: [registry_purchase.registryItem],
      references: [registry_item.id],
      relationName: 'registryItem',
    }),
  }),
);
export const relations_registry_store = relations(registry_store, () => ({}));
export const relations_things_to_do_rels = relations(
  things_to_do_rels,
  ({ one }) => ({
    parent: one(things_to_do, {
      fields: [things_to_do_rels.parent],
      references: [things_to_do.id],
      relationName: '_rels',
    }),
    'things-to-do-categoryID': one(things_to_do_category, {
      fields: [things_to_do_rels['things-to-do-categoryID']],
      references: [things_to_do_category.id],
      relationName: 'things-to-do-category',
    }),
  }),
);
export const relations_things_to_do = relations(
  things_to_do,
  ({ one, many }) => ({
    image: one(media, {
      fields: [things_to_do.image],
      references: [media.id],
      relationName: 'image',
    }),
    _rels: many(things_to_do_rels, {
      relationName: '_rels',
    }),
  }),
);
export const relations_things_to_do_category = relations(
  things_to_do_category,
  () => ({}),
);
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: 'sessions',
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_folders_folder_type = relations(
  payload_folders_folder_type,
  ({ one }) => ({
    parent: one(payload_folders, {
      fields: [payload_folders_folder_type.parent],
      references: [payload_folders.id],
      relationName: 'folderType',
    }),
  }),
);
export const relations_payload_folders = relations(
  payload_folders,
  ({ one, many }) => ({
    folder: one(payload_folders, {
      fields: [payload_folders.folder],
      references: [payload_folders.id],
      relationName: 'folder',
    }),
    folderType: many(payload_folders_folder_type, {
      relationName: 'folderType',
    }),
  }),
);
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    'honeymoon-contributionsID': one(honeymoon_contributions, {
      fields: [payload_locked_documents_rels['honeymoon-contributionsID']],
      references: [honeymoon_contributions.id],
      relationName: 'honeymoon-contributions',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    photoID: one(photo, {
      fields: [payload_locked_documents_rels.photoID],
      references: [photo.id],
      relationName: 'photo',
    }),
    'place-tagID': one(place_tag, {
      fields: [payload_locked_documents_rels['place-tagID']],
      references: [place_tag.id],
      relationName: 'place-tag',
    }),
    'registry-categoryID': one(registry_category, {
      fields: [payload_locked_documents_rels['registry-categoryID']],
      references: [registry_category.id],
      relationName: 'registry-category',
    }),
    'registry-itemID': one(registry_item, {
      fields: [payload_locked_documents_rels['registry-itemID']],
      references: [registry_item.id],
      relationName: 'registry-item',
    }),
    'registry-purchaseID': one(registry_purchase, {
      fields: [payload_locked_documents_rels['registry-purchaseID']],
      references: [registry_purchase.id],
      relationName: 'registry-purchase',
    }),
    'registry-storeID': one(registry_store, {
      fields: [payload_locked_documents_rels['registry-storeID']],
      references: [registry_store.id],
      relationName: 'registry-store',
    }),
    'things-to-doID': one(things_to_do, {
      fields: [payload_locked_documents_rels['things-to-doID']],
      references: [things_to_do.id],
      relationName: 'things-to-do',
    }),
    'things-to-do-categoryID': one(things_to_do_category, {
      fields: [payload_locked_documents_rels['things-to-do-categoryID']],
      references: [things_to_do_category.id],
      relationName: 'things-to-do-category',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    'payload-foldersID': one(payload_folders, {
      fields: [payload_locked_documents_rels['payload-foldersID']],
      references: [payload_folders.id],
      relationName: 'payload-folders',
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: '_rels',
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_honeymoon_contributions_status: typeof enum_honeymoon_contributions_status;
  enum_pages_blocks_content_columns_size: typeof enum_pages_blocks_content_columns_size;
  enum_pages_blocks_photo_gallery_folder: typeof enum_pages_blocks_photo_gallery_folder;
  enum_pages_blocks_stack_direction: typeof enum_pages_blocks_stack_direction;
  enum_pages_status: typeof enum_pages_status;
  enum__pages_v_blocks_content_columns_size: typeof enum__pages_v_blocks_content_columns_size;
  enum__pages_v_blocks_photo_gallery_folder: typeof enum__pages_v_blocks_photo_gallery_folder;
  enum__pages_v_blocks_stack_direction: typeof enum__pages_v_blocks_stack_direction;
  enum__pages_v_version_status: typeof enum__pages_v_version_status;
  enum_registry_purchase_purchased_at: typeof enum_registry_purchase_purchased_at;
  enum_payload_folders_folder_type: typeof enum_payload_folders_folder_type;
  honeymoon_contributions: typeof honeymoon_contributions;
  media: typeof media;
  pages_blocks_accordion_items: typeof pages_blocks_accordion_items;
  pages_blocks_accordion: typeof pages_blocks_accordion;
  pages_blocks_card: typeof pages_blocks_card;
  pages_blocks_content_columns: typeof pages_blocks_content_columns;
  pages_blocks_content: typeof pages_blocks_content;
  pages_blocks_photo_gallery: typeof pages_blocks_photo_gallery;
  pages_blocks_place: typeof pages_blocks_place;
  pages_blocks_registry: typeof pages_blocks_registry;
  pages_blocks_schedule_events: typeof pages_blocks_schedule_events;
  pages_blocks_schedule: typeof pages_blocks_schedule;
  pages_blocks_stack: typeof pages_blocks_stack;
  pages_blocks_things_to_do: typeof pages_blocks_things_to_do;
  pages: typeof pages;
  pages_rels: typeof pages_rels;
  _pages_v_blocks_accordion_items: typeof _pages_v_blocks_accordion_items;
  _pages_v_blocks_accordion: typeof _pages_v_blocks_accordion;
  _pages_v_blocks_card: typeof _pages_v_blocks_card;
  _pages_v_blocks_content_columns: typeof _pages_v_blocks_content_columns;
  _pages_v_blocks_content: typeof _pages_v_blocks_content;
  _pages_v_blocks_photo_gallery: typeof _pages_v_blocks_photo_gallery;
  _pages_v_blocks_place: typeof _pages_v_blocks_place;
  _pages_v_blocks_registry: typeof _pages_v_blocks_registry;
  _pages_v_blocks_schedule_events: typeof _pages_v_blocks_schedule_events;
  _pages_v_blocks_schedule: typeof _pages_v_blocks_schedule;
  _pages_v_blocks_stack: typeof _pages_v_blocks_stack;
  _pages_v_blocks_things_to_do: typeof _pages_v_blocks_things_to_do;
  _pages_v: typeof _pages_v;
  _pages_v_rels: typeof _pages_v_rels;
  photo: typeof photo;
  place_tag: typeof place_tag;
  registry_category: typeof registry_category;
  registry_item: typeof registry_item;
  registry_item_rels: typeof registry_item_rels;
  registry_purchase: typeof registry_purchase;
  registry_store: typeof registry_store;
  things_to_do: typeof things_to_do;
  things_to_do_rels: typeof things_to_do_rels;
  things_to_do_category: typeof things_to_do_category;
  users_sessions: typeof users_sessions;
  users: typeof users;
  payload_kv: typeof payload_kv;
  payload_folders_folder_type: typeof payload_folders_folder_type;
  payload_folders: typeof payload_folders;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_honeymoon_contributions: typeof relations_honeymoon_contributions;
  relations_media: typeof relations_media;
  relations_pages_blocks_accordion_items: typeof relations_pages_blocks_accordion_items;
  relations_pages_blocks_accordion: typeof relations_pages_blocks_accordion;
  relations_pages_blocks_card: typeof relations_pages_blocks_card;
  relations_pages_blocks_content_columns: typeof relations_pages_blocks_content_columns;
  relations_pages_blocks_content: typeof relations_pages_blocks_content;
  relations_pages_blocks_photo_gallery: typeof relations_pages_blocks_photo_gallery;
  relations_pages_blocks_place: typeof relations_pages_blocks_place;
  relations_pages_blocks_registry: typeof relations_pages_blocks_registry;
  relations_pages_blocks_schedule_events: typeof relations_pages_blocks_schedule_events;
  relations_pages_blocks_schedule: typeof relations_pages_blocks_schedule;
  relations_pages_blocks_stack: typeof relations_pages_blocks_stack;
  relations_pages_blocks_things_to_do: typeof relations_pages_blocks_things_to_do;
  relations_pages_rels: typeof relations_pages_rels;
  relations_pages: typeof relations_pages;
  relations__pages_v_blocks_accordion_items: typeof relations__pages_v_blocks_accordion_items;
  relations__pages_v_blocks_accordion: typeof relations__pages_v_blocks_accordion;
  relations__pages_v_blocks_card: typeof relations__pages_v_blocks_card;
  relations__pages_v_blocks_content_columns: typeof relations__pages_v_blocks_content_columns;
  relations__pages_v_blocks_content: typeof relations__pages_v_blocks_content;
  relations__pages_v_blocks_photo_gallery: typeof relations__pages_v_blocks_photo_gallery;
  relations__pages_v_blocks_place: typeof relations__pages_v_blocks_place;
  relations__pages_v_blocks_registry: typeof relations__pages_v_blocks_registry;
  relations__pages_v_blocks_schedule_events: typeof relations__pages_v_blocks_schedule_events;
  relations__pages_v_blocks_schedule: typeof relations__pages_v_blocks_schedule;
  relations__pages_v_blocks_stack: typeof relations__pages_v_blocks_stack;
  relations__pages_v_blocks_things_to_do: typeof relations__pages_v_blocks_things_to_do;
  relations__pages_v_rels: typeof relations__pages_v_rels;
  relations__pages_v: typeof relations__pages_v;
  relations_photo: typeof relations_photo;
  relations_place_tag: typeof relations_place_tag;
  relations_registry_category: typeof relations_registry_category;
  relations_registry_item_rels: typeof relations_registry_item_rels;
  relations_registry_item: typeof relations_registry_item;
  relations_registry_purchase: typeof relations_registry_purchase;
  relations_registry_store: typeof relations_registry_store;
  relations_things_to_do_rels: typeof relations_things_to_do_rels;
  relations_things_to_do: typeof relations_things_to_do;
  relations_things_to_do_category: typeof relations_things_to_do_category;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_folders_folder_type: typeof relations_payload_folders_folder_type;
  relations_payload_folders: typeof relations_payload_folders;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module '@payloadcms/db-vercel-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
