name: Playwright Tests
on:
  deployment_status:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base URL for the tests'
        required: true
        default: 'https://rachelandjack.com'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if:
      ${{ github.event_name == 'workflow_dispatch' || github.event_name ==
      'deployment_status' && github.event.deployment_status.state == 'success'
      }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: npm install -g corepack && corepack enable && pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test
        env:
          BASE_URL:
            ${{ github.event_name == 'deployment_status' &&
            github.event.deployment_status.target_url || inputs.base_url }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
